# Generated by Django 4.2.26 on 2025-11-21 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobAdvertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_number",
                    models.CharField(
                        help_text="Unique post identifier", max_length=100, unique=True
                    ),
                ),
                (
                    "date_posted",
                    models.DateField(help_text="Date when the job was posted"),
                ),
                (
                    "application_deadline",
                    models.DateField(help_text="Application deadline date"),
                ),
                (
                    "post_name",
                    models.CharField(
                        help_text="Job title/position name", max_length=500
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("consultant", "Consultant"),
                            ("temporary", "Temporary Appointment"),
                            ("fixed_term", "Fixed Term Appointment"),
                            ("internship", "Internship"),
                            ("volunteering", "Volunteering"),
                            ("other", "Other"),
                        ],
                        help_text="Type of contract",
                        max_length=50,
                    ),
                ),
                (
                    "contract_duration",
                    models.CharField(
                        blank=True,
                        help_text="Duration of contract (e.g., 12 months, 1 year)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "renewable",
                    models.BooleanField(
                        default=False, help_text="Whether the contract is renewable"
                    ),
                ),
                (
                    "location_region",
                    models.CharField(
                        blank=True,
                        help_text="Geographic region",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "location_country",
                    models.CharField(
                        help_text="Country where the position is based", max_length=200
                    ),
                ),
                (
                    "location_city",
                    models.CharField(
                        blank=True,
                        help_text="City where the position is based (if available)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "work_arrangement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("on-site", "On-site"),
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                        ],
                        help_text="Work arrangement type",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "thematic_area",
                    models.CharField(
                        blank=True,
                        help_text="Thematic area/sector (e.g., Emergency, Fund raising, ICT)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "position_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("consultancy", "Consultancy"),
                            ("g-2", "G-2"),
                            ("g-3", "G-3"),
                            ("g-4", "G-4"),
                            ("g-5", "G-5"),
                            ("g-6", "G-6"),
                            ("g-7", "G-7"),
                            ("internship", "Internship"),
                            ("no-1", "NO-1"),
                            ("no-2", "NO-2"),
                            ("no-3", "NO-3"),
                            ("no-4", "NO-4"),
                            ("p-1", "P-1"),
                            ("p-2", "P-2"),
                            ("p-3", "P-3"),
                            ("p-4", "P-4"),
                            ("p-5", "P-5"),
                            ("d-1", "D-1"),
                            ("d-2", "D-2"),
                            ("other", "Other"),
                        ],
                        help_text="Position level",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "brief_description",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated summary of the job post",
                        null=True,
                    ),
                ),
                (
                    "main_skills_competencies",
                    models.TextField(
                        blank=True,
                        help_text="Main skills and competencies required",
                        null=True,
                    ),
                ),
                (
                    "technical_skills",
                    models.TextField(
                        blank=True, help_text="Technical skills required", null=True
                    ),
                ),
                (
                    "minimum_academic_qualifications",
                    models.TextField(
                        blank=True,
                        help_text="Minimum academic qualifications required",
                        null=True,
                    ),
                ),
                (
                    "minimum_experience",
                    models.TextField(
                        blank=True, help_text="Minimum experience required", null=True
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags for categorization",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Original URL of the job posting",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Advertisement",
                "verbose_name_plural": "Job Advertisements",
                "ordering": ["-date_posted"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the organization (e.g., UNICEF, WFP, UNHCR)",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        blank=True,
                        help_text="Common abbreviation (e.g., UNICEF, WFP)",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Official website URL",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of the organization",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LanguageRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        help_text="Language name (e.g., English, Spanish, French)",
                        max_length=100,
                    ),
                ),
                (
                    "requirement_level",
                    models.CharField(
                        choices=[("required", "Required"), ("preferred", "Preferred")],
                        help_text="Level of requirement for this language",
                        max_length=50,
                    ),
                ),
                (
                    "proficiency_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("basic", "Basic"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("fluent", "Fluent"),
                            ("native", "Native"),
                        ],
                        help_text="Required proficiency level",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        help_text="Associated job advertisement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_requirements",
                        to="core.jobadvertisement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Language Requirement",
                "verbose_name_plural": "Language Requirements",
                "ordering": ["requirement_level", "language"],
            },
        ),
        migrations.AddField(
            model_name="jobadvertisement",
            name="organization",
            field=models.ForeignKey(
                help_text="UN Organization",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="job_advertisements",
                to="core.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="jobadvertisement",
            index=models.Index(
                fields=["organization"], name="core_jobadv_organiz_87375d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobadvertisement",
            index=models.Index(
                fields=["date_posted"], name="core_jobadv_date_po_52d623_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobadvertisement",
            index=models.Index(
                fields=["application_deadline"], name="core_jobadv_applica_370cf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobadvertisement",
            index=models.Index(
                fields=["location_country"], name="core_jobadv_locatio_4d985a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobadvertisement",
            index=models.Index(
                fields=["position_level"], name="core_jobadv_positio_7b467f_idx"
            ),
        ),
    ]
