# Generated by Django 4.2.26 on 2025-11-25 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlerState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        choices=[("unjobs.org", "Unjobs")],
                        help_text="Name of the crawling source",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "last_crawled_post_number",
                    models.CharField(
                        blank=True,
                        help_text="Last post number successfully crawled",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "last_crawl_time",
                    models.DateTimeField(
                        auto_now=True, help_text="When the last crawl was performed"
                    ),
                ),
                (
                    "total_jobs_crawled",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of jobs crawled from this source",
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True,
                        help_text="Last error encountered during crawling",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Crawler State",
                "verbose_name_plural": "Crawler States",
            },
        ),
        migrations.CreateModel(
            name="RawJobData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_number",
                    models.CharField(
                        help_text="Unique post identifier from source",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        help_text="Original URL of the job posting", max_length=500
                    ),
                ),
                (
                    "post_name",
                    models.CharField(
                        blank=True,
                        help_text="Job title/position name",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "post_content",
                    models.TextField(
                        blank=True,
                        help_text="Full job description in markdown format",
                        null=True,
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True,
                        help_text="Organization name as extracted from source",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "location_country",
                    models.CharField(
                        blank=True,
                        help_text="Country as extracted from source",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "location_city",
                    models.CharField(
                        blank=True,
                        help_text="City as extracted from source",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending Processing", "Pending"),
                            ("Currently Processing", "Processing"),
                            ("Successfully Processed", "Processed"),
                            ("Processing Failed", "Failed"),
                            ("Skipped (duplicate or invalid)", "Skipped"),
                        ],
                        default="Pending Processing",
                        help_text="Processing status",
                        max_length=30,
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if processing failed",
                        null=True,
                    ),
                ),
                (
                    "processing_attempts",
                    models.IntegerField(
                        default=0, help_text="Number of processing attempts"
                    ),
                ),
                (
                    "last_processing_attempt",
                    models.DateTimeField(
                        blank=True,
                        help_text="When last processing attempt was made",
                        null=True,
                    ),
                ),
                (
                    "crawled_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this data was crawled"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "job_advertisement",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked processed job advertisement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raw_data",
                        to="core.jobadvertisement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raw Job Data",
                "verbose_name_plural": "Raw Job Data",
                "ordering": ["-crawled_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="core_rawjob_status_c049c5_idx"
                    ),
                    models.Index(
                        fields=["post_number"], name="core_rawjob_post_nu_5e3d89_idx"
                    ),
                    models.Index(
                        fields=["crawled_at"], name="core_rawjob_crawled_0a8868_idx"
                    ),
                ],
            },
        ),
    ]
