# Generated by Django 4.2.26 on 2025-11-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_crawlerstate_rawjobdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawjobdata",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending Processing", "Pending"),
                    ("Downloading Content", "Downloading"),
                    ("Content Downloaded", "Downloaded"),
                    ("Currently Processing", "Processing"),
                    ("Successfully Processed", "Processed"),
                    ("Processing Failed", "Failed"),
                    ("Skipped (duplicate or invalid)", "Skipped"),
                ],
                default="Pending Processing",
                help_text="Processing status",
                max_length=30,
            ),
        ),
    ]
